import {
  extractLabelUrlFromShipmentRow,
  findShipmentRowForOrder,
  imageBufferToPdf,
  isPdfBuffer,
  isStaleFallbackLabelCache,
} from "./velocity.labelPdf.js";

describe("velocity.labelPdf helpers", () => {
  it("extracts label_url from shipment attributes", () => {
    const row = {
      attributes: {
        awb_code: "AWB123",
        label_url: "https://example.com/label.pdf",
      },
    };
    expect(extractLabelUrlFromShipmentRow(row)).toBe("https://example.com/label.pdf");
  });

  it("finds shipment row by AWB", () => {
    const rows = [
      { attributes: { awb_code: "OTHER" } },
      { attributes: { tracking_number: "AWB999", label_url: "https://x/y.pdf" } },
    ];
    const match = findShipmentRowForOrder(rows, { awb: "AWB999" });
    expect(match).toBe(rows[1]);
    expect(extractLabelUrlFromShipmentRow(match!)).toBe("https://x/y.pdf");
  });

  it("detects PDF magic bytes", () => {
    expect(isPdfBuffer(Buffer.from("%PDF-1.4\n"))).toBe(true);
    expect(isPdfBuffer(Buffer.from("NOTPDF"))).toBe(false);
  });

  it("detects stale fallback cache PDFs", () => {
    const buf = Buffer.from("prefix fallback label generated by ShipAmaze suffix");
    expect(isStaleFallbackLabelCache(buf)).toBe(true);
    expect(isStaleFallbackLabelCache(Buffer.from("%PDF-real-courier"))).toBe(false);
  });

  it("converts image labels to fixed 4x6 PDF pages", async () => {
    // 1×1 PNG
    const png = Buffer.from(
      "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==",
      "base64"
    );
    const pdf = await imageBufferToPdf(png, "image/png");
    expect(isPdfBuffer(pdf)).toBe(true);
    expect(pdf.length).toBeLessThan(50_000);
  });
});
