import type { IOrder } from "../../models/Order.js";
import { AppError } from "../../middleware/errorMiddleware.js";
import * as velocityService from "./velocity.service.js";

export type ResolvedLabelPdf = {
  buffer: Buffer;
  contentType: string;
  source?: "cache" | "courier";
};

export type VelocityRefreshCache = {
  rowsBySearch: Map<string, Record<string, unknown>[]>;
  inflight: Map<string, Promise<Record<string, unknown>[]>>;
};

export type ResolveOrderLabelPdfOpts = {
  persistCache?: boolean;
  /** When false, skip Velocity listShipments refresh (bulk fast path). */
  allowVelocityRefresh?: boolean;
  fetchTimeoutMs?: number;
  velocityRefreshCache?: VelocityRefreshCache;
};

function getShipmentAttrs(row: Record<string, unknown>): Record<string, unknown> {
  return (row.attributes != null && typeof row.attributes === "object" ? row.attributes : row) as Record<
    string,
    unknown
  >;
}

export function extractLabelUrlFromShipmentRow(row: Record<string, unknown>): string {
  const attrs = getShipmentAttrs(row);
  return String(
    attrs.label_url ??
      attrs.amazon_label_url ??
      attrs.labelUrl ??
      attrs.shipping_label_url ??
      attrs.pdf_url ??
      attrs.label ??
      ""
  ).trim();
}

export function findShipmentRowForOrder(
  rows: Record<string, unknown>[],
  order: Pick<IOrder, "awb" | "trackingId" | "velocityOrderId" | "velocityShipmentId" | "shipmentId">
): Record<string, unknown> | undefined {
  const awb = String(order.awb || order.trackingId || "").trim();
  const velOrderId = String(order.velocityOrderId || "").trim();
  const velShipmentId = String(order.velocityShipmentId || order.shipmentId || "").trim();

  for (const row of rows) {
    const attrs = getShipmentAttrs(row);
    if (awb) {
      const candidates = [attrs.tracking_number, attrs.awb, attrs.awb_code, attrs.trackingNumber];
      if (candidates.some((v) => String(v ?? "").trim() === awb)) return row;
    }
    if (velOrderId) {
      const candidates = [attrs.order_id, attrs.provider_order_id, attrs.client_order_id];
      if (candidates.some((v) => String(v ?? "").trim() === velOrderId)) return row;
    }
    if (velShipmentId) {
      const candidates = [attrs.shipment_id, attrs.id, attrs.velocity_shipment_id];
      if (candidates.some((v) => String(v ?? "").trim() === velShipmentId)) return row;
    }
  }

  if (rows.length === 1) return rows[0];
  return undefined;
}

export function isPdfBuffer(buf: Buffer): boolean {
  return buf.length >= 4 && buf.subarray(0, 4).toString("ascii") === "%PDF";
}

/** Old server-generated fallback labels must not be served as courier PDFs. */
export function isStaleFallbackLabelCache(buf: Buffer): boolean {
  const sample = buf.subarray(0, Math.min(buf.length, 12_000)).toString("latin1");
  return sample.includes("fallback label generated by ShipAmaze");
}

function isPngBuffer(buf: Buffer): boolean {
  return buf.length >= 8 && buf[0] === 0x89 && buf[1] === 0x50 && buf[2] === 0x4e && buf[3] === 0x47;
}

function isJpegBuffer(buf: Buffer): boolean {
  return buf.length >= 3 && buf[0] === 0xff && buf[1] === 0xd8 && buf[2] === 0xff;
}

function detectLabelContentType(buf: Buffer, headerContentType: string): string {
  const ct = String(headerContentType || "").toLowerCase();
  if (isPdfBuffer(buf)) return "application/pdf";
  if (ct.includes("pdf")) return "application/pdf";
  if (ct.includes("png") || isPngBuffer(buf)) return "image/png";
  if (ct.includes("jpeg") || ct.includes("jpg") || isJpegBuffer(buf)) return "image/jpeg";
  if (ct.includes("octet-stream") && isPdfBuffer(buf)) return "application/pdf";
  return ct || "application/octet-stream";
}

async function fetchUrlWithTimeout(url: string, timeoutMs: number): Promise<Response> {
  const ac = new AbortController();
  const timer = setTimeout(() => ac.abort(), timeoutMs);
  try {
    return await fetch(url, { signal: ac.signal, redirect: "follow" });
  } finally {
    clearTimeout(timer);
  }
}

async function imageBufferToPdf(buffer: Buffer, contentType: string): Promise<Buffer> {
  const { PDFDocument } = await import("pdf-lib");
  const doc = await PDFDocument.create();
  const image =
    contentType.includes("png") || isPngBuffer(buffer)
      ? await doc.embedPng(buffer)
      : await doc.embedJpg(buffer);
  const page = doc.addPage([image.width, image.height]);
  page.drawImage(image, { x: 0, y: 0, width: image.width, height: image.height });
  return Buffer.from(await doc.save());
}

async function normalizeLabelToPdf(buffer: Buffer, contentType: string): Promise<{ buffer: Buffer; contentType: string }> {
  const detected = detectLabelContentType(buffer, contentType);
  if (detected.includes("pdf") || isPdfBuffer(buffer)) {
    return { buffer, contentType: "application/pdf" };
  }
  if (detected.includes("png") || detected.includes("jpeg") || detected.includes("jpg")) {
    return { buffer: await imageBufferToPdf(buffer, detected), contentType: "application/pdf" };
  }
  throw new AppError(502, "Label URL did not return a PDF or image");
}

async function fetchLabelBytes(
  url: string,
  timeoutMs: number
): Promise<{ buffer: Buffer; contentType: string } | null> {
  const r = await fetchUrlWithTimeout(url, timeoutMs);
  if (!r.ok) return null;
  const headerCt = r.headers.get("content-type") || "";
  const raw = Buffer.from(await r.arrayBuffer());
  if (raw.length === 0) return null;

  const detected = detectLabelContentType(raw, headerCt);
  if (
    isPdfBuffer(raw) ||
    detected.includes("pdf") ||
    detected.includes("png") ||
    detected.includes("jpeg") ||
    detected.includes("jpg") ||
    detected.includes("octet-stream") ||
    url.toLowerCase().includes(".pdf")
  ) {
    return { buffer: raw, contentType: detected };
  }
  return null;
}

function createRefreshCache(): VelocityRefreshCache {
  return { rowsBySearch: new Map(), inflight: new Map() };
}

async function getShipmentRows(search: string, cache?: VelocityRefreshCache): Promise<Record<string, unknown>[]> {
  const key = search.trim();
  if (!key) return [];

  if (!cache) {
    const result = await velocityService.listShipments({ search: key });
    return Array.isArray(result.data) ? (result.data as Record<string, unknown>[]) : [];
  }

  const hit = cache.rowsBySearch.get(key);
  if (hit) return hit;

  let inflight = cache.inflight.get(key);
  if (!inflight) {
    inflight = velocityService
      .listShipments({ search: key })
      .then((result) => {
        const rows = Array.isArray(result.data) ? (result.data as Record<string, unknown>[]) : [];
        cache.rowsBySearch.set(key, rows);
        cache.inflight.delete(key);
        return rows;
      })
      .catch(() => {
        cache.inflight.delete(key);
        cache.rowsBySearch.set(key, []);
        return [];
      });
    cache.inflight.set(key, inflight);
  }
  return inflight;
}

async function refreshLabelUrlFromVelocity(
  order: IOrder,
  cache?: VelocityRefreshCache
): Promise<string | null> {
  const awb = String(order.awb || order.trackingId || "").trim();
  const velOrderId = String(order.velocityOrderId || order.orderId || "").trim();
  const velShipmentId = String(order.velocityShipmentId || order.shipmentId || "").trim();

  const searches = [...new Set([awb, velOrderId, velShipmentId].filter(Boolean))];
  for (const search of searches) {
    const rows = await getShipmentRows(search, cache);
    const row = findShipmentRowForOrder(rows, order);
    if (!row) continue;
    const freshUrl = extractLabelUrlFromShipmentRow(row);
    if (freshUrl) return freshUrl;
  }
  return null;
}

/** Fetch courier label PDF for an order (cache in DB when resolved). */
export async function resolveOrderLabelPdf(
  order: IOrder,
  opts: ResolveOrderLabelPdfOpts = {}
): Promise<ResolvedLabelPdf> {
  const persistCache = opts.persistCache !== false;
  const allowVelocityRefresh = opts.allowVelocityRefresh !== false;
  const fetchTimeoutMs = opts.fetchTimeoutMs ?? 12_000;
  const cache = opts.velocityRefreshCache;

  const cachedPdf = String(order.labelPdfBase64 ?? "").trim();
  if (cachedPdf) {
    const buf = Buffer.from(cachedPdf, "base64");
    if (isStaleFallbackLabelCache(buf)) {
      order.labelPdfBase64 = undefined;
      order.labelPdfContentType = undefined;
      order.labelPdfCachedAt = undefined;
      await order.save().catch(() => undefined);
    } else {
      const normalized = await normalizeLabelToPdf(buf, String(order.labelPdfContentType || "application/pdf")).catch(
        () => ({ buffer: buf, contentType: "application/pdf" })
      );
      return { ...normalized, source: "cache" };
    }
  }

  let labelUrl = String(order.labelUrl || order.manifestUrl || "").trim();
  let fetched: { buffer: Buffer; contentType: string } | null = null;

  if (labelUrl) {
    fetched = await fetchLabelBytes(labelUrl, fetchTimeoutMs).catch(() => null);
  }

  if (!fetched && allowVelocityRefresh) {
    const freshUrl = await refreshLabelUrlFromVelocity(order, cache).catch(() => null);
    if (freshUrl) {
      if (freshUrl !== labelUrl) {
        order.labelUrl = freshUrl;
        labelUrl = freshUrl;
      }
      fetched = await fetchLabelBytes(freshUrl, fetchTimeoutMs).catch(() => null);
    }
  }

  if (!fetched) {
    if (!labelUrl) {
      throw new AppError(
        404,
        `No label URL for order ${order.orderId}. Re-create the shipment in Velocity to generate a new label.`
      );
    }

    throw new AppError(
      502,
      `Label PDF unavailable for order ${order.orderId}. The courier URL may have expired — recreate the shipment or refresh tracking.`
    );
  }

  const normalized = await normalizeLabelToPdf(fetched.buffer, fetched.contentType);

  if (persistCache) {
    order.labelPdfBase64 = normalized.buffer.toString("base64");
    order.labelPdfContentType = normalized.contentType;
    order.labelPdfCachedAt = new Date();
    await order.save().catch(() => undefined);
  }

  return { ...normalized, source: "courier" };
}

/** Download and cache courier PDF while presigned label_url is still valid. */
export function scheduleLabelPdfCache(order: IOrder): void {
  if (!String(order.labelUrl || "").trim()) return;
  if (String(order.labelPdfBase64 ?? "").trim()) return;
  void resolveOrderLabelPdf(order, {
    allowVelocityRefresh: false,
    persistCache: true,
  }).catch(() => undefined);
}

export function createVelocityRefreshCache(): VelocityRefreshCache {
  return createRefreshCache();
}

/** Run async tasks with a concurrency cap (avoids flooding Velocity / Mongo). */
export async function mapWithConcurrency<T, R>(
  items: T[],
  limit: number,
  fn: (item: T, index: number) => Promise<R>
): Promise<R[]> {
  if (items.length === 0) return [];
  const cap = Math.max(1, Math.min(limit, items.length));
  const results = new Array<R>(items.length);
  let next = 0;

  async function worker() {
    for (;;) {
      const idx = next;
      next += 1;
      if (idx >= items.length) return;
      results[idx] = await fn(items[idx], idx);
    }
  }

  await Promise.all(Array.from({ length: cap }, () => worker()));
  return results;
}
