// CSV and PDF export utilities

type CsvCell = string | number | boolean | null | undefined;

function csvCell(cell: CsvCell): string {
  return `"${String(cell ?? "").replace(/"/g, '""')}"`;
}

export function downloadCSV(filename: string, headers: string[], rows: CsvCell[][]) {
  const csvContent = [
    headers.map(csvCell).join(','),
    ...rows.map(row => row.map(csvCell).join(','))
  ].join('\n');
  
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${filename}.csv`;
  link.click();
  URL.revokeObjectURL(url);
}

export function downloadPDF(filename: string, title: string, headers: string[], rows: (string | number)[][], summaryLines?: string[]) {
  // Generate a printable HTML table and trigger print/save as PDF
  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>${title}</title>
      <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Segoe UI', Arial, sans-serif; padding: 40px; color: #1a1a2e; }
        .header { display: flex; align-items: center; justify-content: space-between; margin-bottom: 30px; padding-bottom: 20px; border-bottom: 3px solid #4F46E5; }
        .header h1 { font-size: 22px; color: #4F46E5; }
        .header .meta { font-size: 12px; color: #6b7280; text-align: right; }
        .summary { display: flex; gap: 20px; margin-bottom: 24px; flex-wrap: wrap; }
        .summary-item { background: #f3f4f6; border-radius: 8px; padding: 12px 20px; flex: 1; min-width: 150px; }
        .summary-item .label { font-size: 11px; color: #6b7280; text-transform: uppercase; letter-spacing: 0.5px; }
        .summary-item .value { font-size: 18px; font-weight: 700; color: #1a1a2e; margin-top: 2px; }
        table { width: 100%; border-collapse: collapse; font-size: 13px; }
        th { background: #4F46E5; color: white; padding: 10px 12px; text-align: left; font-weight: 600; }
        td { padding: 9px 12px; border-bottom: 1px solid #e5e7eb; }
        tr:nth-child(even) { background: #f9fafb; }
        tr:hover { background: #eef2ff; }
        .footer { margin-top: 30px; padding-top: 15px; border-top: 1px solid #e5e7eb; font-size: 11px; color: #9ca3af; text-align: center; }
        @media print { body { padding: 20px; } .no-print { display: none; } }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>📦 ${title}</h1>
        <div class="meta">
          <div>ShipAmaze Logistics</div>
          <div>Generated: ${new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })}</div>
        </div>
      </div>
      ${summaryLines ? `<div class="summary">${summaryLines.map(s => {
        const [label, value] = s.split(':');
        return `<div class="summary-item"><div class="label">${label.trim()}</div><div class="value">${value.trim()}</div></div>`;
      }).join('')}</div>` : ''}
      <table>
        <thead><tr>${headers.map(h => `<th>${h}</th>`).join('')}</tr></thead>
        <tbody>${rows.map(row => `<tr>${row.map(cell => `<td>${cell}</td>`).join('')}</tr>`).join('')}</tbody>
      </table>
      <div class="footer">Report generated by ShipAmaze · www.shipamaze.example</div>
      <script>window.onload = function() { window.print(); }</script>
    </body>
    </html>
  `;
  
  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(html);
    printWindow.document.close();
  }
}
